#!/bin/bash
assert() {
  expected="$1"
  input="$2"

  ./9cc "$input" > tmp.s
  gcc -o tmp tmp.s
  ./tmp
  actual="$?"

  if [ "$actual" = "$expected" ]; then
    echo "$input => $actual"
  else
    echo "$input => $expected expected, but got $actual"
    exit 1
  fi
}

assert 10  './test/test92.txt'
assert 6 './test/test91.txt'
assert 0  './test/test90.txt'
assert 7  './test/test89.txt'
assert 0  './test/test88.txt'
assert 1  './test/test87.txt'
assert 2  './test/test86.txt'
assert 3  './test/test85.txt'
assert 4  './test/test84.txt'
assert 16 './test/test83.txt'
assert 23 './test/test82.txt'
assert 46 './test/test81.txt'
assert 30 './test/test80.txt'
assert 4  './test/test79.txt'
assert 3  './test/test78.txt'
assert 20 './test/test77.txt'
assert 3  './test/test76.txt'
assert 4  './test/test75.txt'
assert 8  './test/test74.txt'
assert 4  './test/test73.txt'
assert 8  './test/test72.txt'
assert 4  './test/test71.txt'
assert 4 './test/test70.txt'
assert 1  './test/test69.txt'
assert 1  './test/test68.txt'
assert 73 './test/test67.txt'
assert 32 './test/test66.txt'
assert 7  './test/test65.txt'
assert 5  './test/test64.txt'
assert 3  './test/test63.txt'
assert 3  './test/test62.txt'
assert 0  './test/test61.txt'
assert 3  './test/test60.txt'
assert 5  './test/test59.txt'
assert 3  './test/test58.txt'
assert 3  './test/test57.txt'
assert 3  './test/test56.txt'
assert 34 './test/test55.txt'
assert 5  './test/test54.txt'
assert 10 './test/test53.txt'
assert 5  './test/test52.txt'
assert 11 './test/test51.txt'
assert 0  './test/test50.txt'
assert 60   './test/test49.txt'
assert 15  './test/test48.txt'
assert 5  './test/test47.txt'
assert 6  './test/test46.txt'
assert 5  './test/test45.txt'
assert 2  './test/test44.txt'
assert 3  './test/test43.txt'
assert 1  './test/test42.txt'
assert 0  './test/test41.txt'
assert 0  './test/test40.txt'
assert 42   './test/test39.txt'
assert 21  './test/test38.txt'
assert 41  './test/test37.txt'
assert 47  './test/test36.txt'
assert 15  './test/test35.txt'
assert 4  './test/test34.txt'
assert 10  './test/test33.txt'
assert 10  './test/test32.txt'
assert 10  './test/test31.txt'
assert 10  './test/test30.txt'
assert 10  './test/test29.txt'
assert 10  './test/test28.txt'
assert 10   './test/test27.txt'
assert 0  './test/test26.txt'
assert 1  './test/test25.txt'
assert 1  './test/test24.txt'
assert 0  './test/test23.txt'
assert 1  './test/test22.txt'
assert 0  './test/test21.txt'
assert 0  './test/test20.txt'
assert 1  './test/test19.txt'
assert 1  './test/test18.txt'
assert 0  './test/test17.txt'
assert 1  './test/test16.txt'
assert 0  './test/test15.txt'
assert 0  './test/test14.txt'
assert 1  './test/test13.txt'
assert 1  './test/test12.txt'
assert 0  './test/test11.txt'
assert 3  './test/test10.txt'
assert 8  './test/test9.txt'
assert 3 './test/test8.txt'
assert 8  './test/test7.txt'
assert 6  './test/test6.txt'
assert 3  './test/test5.txt'
assert 8  './test/test4.txt'
assert 1  './test/test3.txt'
assert 2  './test/test2.txt'
assert 3  './test/test1.txt'
